doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_sqlite'
        charset: 'UTF-8'

        # With Symfony 3.3, remove the `resolve:` prefix
        url: 'sqlite:///%kernel.project_dir%/var/data.db'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
